name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # can on GitHub infrastructure if set to ubuntu-latest and our own infrastructure if set to self-hosted
    runs-on: ubuntu-latest
    # steps for continuous integration
    steps:
      - name: clone-this-repo
        # to clone use actions GitHub account checkout repo release tag v3
        uses: actions/checkout@v3
      - name: setup-node-js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install-node-modules
        run: npm i
        run: npm install pm2 -g
#      - name: auto-format-code
#        run: npm run format
#      - name: commit-and-push
#        uses: EndBug/add-and-commit@v9
#        with:
#         default_author: github_actions
      - name: restart-express-server
        run: pm2 restart SDR
      - name: Make angular build
        run: ng build
        # run unit tests using mocha chai
        # run linting checks using eslint
